server:
  http2:
    enabled: true
  port: '8081'
  servlet:
    session:
      timeout: 1d
      cookie:
        secure: true
        name: session_id
spring:
  liquibase:
    enabled: true
    change-log: 'classpath:liquibase/db-changelog.yaml'
  datasource:
    url: '${DB_URL}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    hikari:
      schema: chess
  session:
    store-type: jdbc
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: 'file:chess/static/'
      cache:
        cachecontrol:
          max-age: 1d