--liquibase formatted sql

--changeset author:lizunya runOnChange:true

    CREATE TABLE IF NOT EXISTS session (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
      updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
      white_ip VARCHAR(255) NOT NULL,
      black_ip VARCHAR(255) NOT NULL,
      CONSTRAINT pk_session PRIMARY KEY (id)
    );