--liquibase formatted sql

--changeset author:lizunya

    CREATE TABLE IF NOT EXISTS session_message (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      session_id BIGINT NOT NULL,
      user_id BIGINT NOT NULL,
      payload VARCHAR(200) NOT NULL,
      CONSTRAINT pk_session_message PRIMARY KEY (id),
      CONSTRAINT fk_message_to_session FOREIGN KEY(session_id) REFERENCES session(id),
      CONSTRAINT fk_message_to_user FOREIGN KEY(user_id) REFERENCES user(id)
    );