--liquibase formatted sql

--changeset author:lizunya

    CREATE TABLE IF NOT EXISTS session (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      white_player_id BIGINT NOT NULL,
      black_player_id BIGINT NOT NULL,
      status VARCHAR(50) NOT NULL,
      CONSTRAINT pk_session PRIMARY KEY (id),
      CONSTRAINT fk_session_to_user FOREIGN KEY(white_player_id, black_player_id) REFERENCES user(id)

    );