--liquibase formatted sql

--changeset author:lizunya

    CREATE TABLE IF NOT EXISTS user (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      ip VARCHAR(200) NOT NULL,
      name VARCHAR(50) NOT NULL,
      bot BOOLEAN NOT NULL,
      CONSTRAINT pk_user PRIMARY KEY (id),
      CONSTRAINT uq_user_ip UNIQUE(ip)
    );