name: reviewdog

on: [ pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          filter_mode: file
          reporter: github-pr-review
          github_token: ${{ secrets.github_token }}
